# Generated by Django 5.2.6 on 2025-09-15 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RequestsInternal',
            new_name='Requests',
        ),
        migrations.DeleteModel(
            name='RequestsCustomer',
        ),
    ]
